import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<script src="http://localhost:8097"></script>
			</head>
			<body className={`${sora.className}`}>
				<Navbar />
				<div className="">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
