import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${sora.className}`}>
				<Navbar />
				<div className="md:min-h-screen min-h-[550px]">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
